{% set name = "choclo" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/choclo-{{ version }}.tar.gz
  sha256: 3dd2dad1cf9277fe1f55f643aa53b9fad23d6012df4539269b7d8a9b2bc5ebc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=64
    - setuptools_scm >=8.0.3
  run:
    - python >=3.8
    - numpy >=1.19
    - numba >=0.52

test:
  imports:
    - choclo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fatiando/choclo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Kernel functions for your geophysical models
  description: |
    Choclo is a Python library that hosts optimized forward modelling and
    kernel functions for running geophysical forward and inverse models,
    intended to be used by other libraries as the underlying layer of their
    computation.
  doc_url: https://www.fatiando.org/choclo
  dev_url: https://github.com/fatiando/choclo

extra:
  recipe-maintainers:
    - santisoler
    - leouieda
