{% set name = "choclo" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/choclo-{{ version }}.tar.gz
  sha256: e0d7c76c99512e601a058b55af74ab989b6b2814b6edf22b39c1cf4476c18cc9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=6.2
  run:
    - python >=3.6
    - numpy >=1.19
    - numba >=0.52

test:
  imports:
    - choclo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fatiando/choclo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Kernel functions for your geophysical models
  description: |
    Choclo is a Python library that hosts optimized forward modelling and
    kernel functions for running geophysical forward and inverse models,
    intended to be used by other libraries as the underlying layer of their
    computation.
  doc_url: https://www.fatiando.org/choclo
  dev_url: https://github.com/fatiando/choclo

extra:
  recipe-maintainers:
    - santisoler
    - leouieda
