{% set name = "choclo" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/choclo-{{ version }}.tar.gz
  sha256: 44869d72c260ac4cf058e325af29672bf295822b4514856dfeb59cb9a66d5982

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - setuptools_scm >=8.0.3
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - numba >=0.52

test:
  imports:
    - choclo
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/fatiando/choclo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Kernel functions for your geophysical models
  description: |
    Choclo is a Python library that hosts optimized forward modelling and
    kernel functions for running geophysical forward and inverse models,
    intended to be used by other libraries as the underlying layer of their
    computation.
  doc_url: https://www.fatiando.org/choclo
  dev_url: https://github.com/fatiando/choclo

extra:
  recipe-maintainers:
    - santisoler
    - leouieda
